/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package tiendita.com.tienda.entities;

public class Product {
    private java.lang.String average_rating;

    public void setAverage_rating(java.lang.String average_rating) {
        this.average_rating = average_rating;
    }

    public java.lang.String getAverage_rating() {
        return average_rating;
    }

    private java.lang.Integer total_sales;

    public void setTotal_sales(java.lang.Integer total_sales) {
        this.total_sales = total_sales;
    }

    public java.lang.Integer getTotal_sales() {
        return total_sales;
    }

    private java.lang.String date_modified;

    public void setDate_modified(java.lang.String date_modified) {
        this.date_modified = date_modified;
    }

    public java.lang.String getDate_modified() {
        return date_modified;
    }

    private java.lang.String catalog_visibility;

    public void setCatalog_visibility(java.lang.String catalog_visibility) {
        this.catalog_visibility = catalog_visibility;
    }

    public java.lang.String getCatalog_visibility() {
        return catalog_visibility;
    }

    private java.lang.Boolean featured;

    public void setFeatured(java.lang.Boolean featured) {
        this.featured = featured;
    }

    public java.lang.Boolean getFeatured() {
        return featured;
    }

    private java.lang.Object stock_quantity;

    public void setStock_quantity(java.lang.Object stock_quantity) {
        this.stock_quantity = stock_quantity;
    }

    public java.lang.Object getStock_quantity() {
        return stock_quantity;
    }

    private java.lang.Integer menu_order;

    public void setMenu_order(java.lang.Integer menu_order) {
        this.menu_order = menu_order;
    }

    public java.lang.Integer getMenu_order() {
        return menu_order;
    }

    private java.lang.String tax_class;

    public void setTax_class(java.lang.String tax_class) {
        this.tax_class = tax_class;
    }

    public java.lang.String getTax_class() {
        return tax_class;
    }

    private java.lang.String date_created;

    public void setDate_created(java.lang.String date_created) {
        this.date_created = date_created;
    }

    public java.lang.String getDate_created() {
        return date_created;
    }

    private java.lang.String shipping_class;

    public void setShipping_class(java.lang.String shipping_class) {
        this.shipping_class = shipping_class;
    }

    public java.lang.String getShipping_class() {
        return shipping_class;
    }

    private java.lang.String weight;

    public void setWeight(java.lang.String weight) {
        this.weight = weight;
    }

    public java.lang.String getWeight() {
        return weight;
    }

    private java.lang.Object[] upsell_ids;

    public void setUpsell_ids(java.lang.Object[] upsell_ids) {
        this.upsell_ids = upsell_ids;
    }

    public java.lang.Object[] getUpsell_ids() {
        return upsell_ids;
    }

    private java.lang.String purchase_note;

    public void setPurchase_note(java.lang.String purchase_note) {
        this.purchase_note = purchase_note;
    }

    public java.lang.String getPurchase_note() {
        return purchase_note;
    }

    private java.lang.String button_text;

    public void setButton_text(java.lang.String button_text) {
        this.button_text = button_text;
    }

    public java.lang.String getButton_text() {
        return button_text;
    }

    private java.lang.String short_description;

    public void setShort_description(java.lang.String short_description) {
        this.short_description = short_description;
    }

    public java.lang.String getShort_description() {
        return short_description;
    }

    private java.lang.String regular_price;

    public void setRegular_price(java.lang.String regular_price) {
        this.regular_price = regular_price;
    }

    public java.lang.String getRegular_price() {
        return regular_price;
    }

    private java.lang.String name;

    public void setName(java.lang.String name) {
        this.name = name;
    }

    public java.lang.String getName() {
        return name;
    }

    private java.lang.Boolean purchasable;

    public void setPurchasable(java.lang.Boolean purchasable) {
        this.purchasable = purchasable;
    }

    public java.lang.Boolean getPurchasable() {
        return purchasable;
    }
    private java.lang.Boolean in_stock;
    public void setIn_stock(java.lang.Boolean in_stock) {
        this.in_stock = in_stock;
    }
    public java.lang.Boolean getIn_stock() {
        return in_stock;
    }
    private java.lang.String price;
    public java.lang.String getPrice() {
        return price;
    }
    private Image[] images;
    public Image[] getImages() {
        return images;
    }
    private java.lang.Integer id;
    public void setId(java.lang.Integer id) {
        this.id = id;
    }
    public java.lang.Integer getId() {
        return id;
    }
    private java.lang.String description;
    public void setDescription(java.lang.String description) {
        this.description = description;
    }
    public java.lang.String getDescription() {
        return description;
    }

}